main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_url'),
    path('blog/', views.BlogView.as_view(), name='blog_url'),
    path('blog/<int:id>', views.BlogDetailView.as_view(), name='blogdetail_url'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('contacts/', include('sendemail.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sendemail/urls.py
from django.contrib import admin
from django.urls import path

from .views import contactView, successView

urlpatterns = [
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
]

main/models.py
from django.db import models


class Portfolio(models.Model):
    image = models.ImageField(upload_to='uploads/portfolio/%Y/%m/%d')
    title = models.CharField(max_length=100)
    project = models.CharField(max_length=50)
    client = models.CharField(max_length=50)
    duration = models.CharField(max_length=50)
    technologies = models.CharField(max_length=50)
    budjet = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Portfolio'
        verbose_name_plural = 'Portfolios'


class BlogPost(models.Model):
    image = models.ImageField(upload_to='uploads/Blog/%Y/%m/%d')
    title = models.CharField(max_length=100)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'


class AboutMe(models.Model):
    image = models.ImageField(upload_to='uploads/About/%Y/%m/%d', default=True)
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    birthdate = models.CharField(max_length=255, blank=True)
    nationality = models.CharField(max_length=255, blank=True)
    experience = models.CharField(max_length=255, blank=True)
    address = models.CharField(max_length=255, blank=True)
    freelance = models.CharField(max_length=255, blank=True)
    languages = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=255, blank=True)
    email = models.CharField(max_length=255, blank=True)
    telegram = models.CharField(max_length=255, blank=True)
    instagram = models.CharField(max_length=255, blank=True)
    my_cv = models.CharField(max_length=255, blank=True)
    file = models.FileField(default=True, upload_to='files')

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Info'
        verbose_name_plural = 'Info'

class Experience(models.Model):
    about = models.ForeignKey(AboutMe, on_delete=models.CASCADE, related_name='experience_about')
    date = models.CharField(max_length=10, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()


class Education(models.Model):
    about = models.ForeignKey(AboutMe, on_delete=models.CASCADE, related_name='education_about')
    date = models.CharField(max_length=10, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()

sendemail/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    comment = forms.CharField(widget=forms.Textarea, required=True)

sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    comment = forms.CharField(widget=forms.Textarea, required=True)

main/views.py
from django.views import generic
from . import models


# Create your views here.


class HomeView(generic.TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['portfolios'] = models.Portfolio.objects.all()
        context['blogs'] = models.BlogPost.objects.all()
        context['info'] = models.AboutMe.objects.first()
        return context


class BlogView(generic.ListView):
    model = models.BlogPost
    template_name = 'pages/blog.html'
    context_object_name = 'blogs'


class BlogDetailView(generic.DetailView):
    model = models.BlogPost
    template_name = 'pages/blogdetail.html'
    pk_url_kwarg = 'id'

sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from myblog.settings import EMAIL_HOST_USER
from .forms import ContactForm

def contactView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            comment = form.cleaned_data['comment']
            try:
                send_mail(name, comment, EMAIL_HOST_USER, [email])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "pages/home.html", {'form': form})

def successView(request):
    return HttpResponse('Success! Thank you for your message.')

templates/base/base.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Istanbul - Personal Portfolio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">


        <!-- Template Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
              rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

        <!-- Template CSS Files -->
        <link type="text/css" media="all" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link type="text/css" media="all" href="{% static 'css/jquery.animatedheadline.css' %}" rel="stylesheet">
        <link type="text/css" media="all" href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link type="text/css" media="all" href="{% static 'css/style.css' %}" rel="stylesheet">
        <link type="text/css" media="all" href="{% static 'css/skins/yellow.css' %}" rel="stylesheet">

        <!-- Template JS Files -->
        <script src="{% static 'js/modernizr.js' %}"></script>

        <!-- Live Style Switcher - demo only -->
        <link rel="alternate stylesheet" type="text/css" title="blue" href="{% static 'css/skins/blue.css' %}"/>
        <link rel="alternate stylesheet" type="text/css" title="goldenrod" href="{% static 'css/skins/goldrenrod.css' %}"/>
        <link rel="alternate stylesheet" type="text/css" title="green" href="{% static 'css/skins/green.css' %}"/>
        <link rel="alternate stylesheet" type="text/css" title="magenta" href="{% static 'css/skins/magenta.css' %}"/>
        <link rel="alternate stylesheet" type="text/css" title="orange" href="{% static 'css/skins/orange.css' %}"/>
        <link rel="alternate stylesheet" type="text/css" title="red" href="{% static 'css/skins/red.css' %}"/>
        <link rel="alternate stylesheet" type="text/css" title="yellow" href="{% static 'css/skins/yellow.css' %}"/>
        <link rel="alternate stylesheet" type="text/css" title="yellowgreen" href="{% static 'css/skins/yellowgreen.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/styleswitcher.css' %}"/>

    </head>

    <body class="dark fullscreendark">
    <div class="page">
        {% include 'include/switcher.html' %}
        {% include 'include/header.html' %}
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Preloader Starts -->
    <div class="preloader">
        <div class="preloader-container">
            <h1>daria</h1>
            <div id="progress-line-container">
                <div class="progress-line"></div>
            </div>
            <h1>taylor</h1>
        </div>
    </div>
    <!-- Preloader Ends -->

    <!-- Template JS Files -->
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/jquery.animatedheadline.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/transition.js' %}"></script>
    <!-- Live Style Switcher JS File - only demo -->
    <script src="{% static 'js/styleswitcher.js' %}"></script>
    <!-- Main JS Initialization File -->
    <script src="{% static 'js/custom.js' %}"></script>
    </body>

</html>

templates/include/header.html
<!-- Header Starts -->
    <header id="header">
		<div class="nav-container">
			<div>
				<!-- Mobile Navigation Starts -->
				<ul id="nav" class="navigation">
					<li class="active">
						<div>
							<a id="link-home" href="index-dark.html#home" class="active">
								<i class="fa fa-home"></i><span>Home</span>
							</a>
						</div>
					</li>
					<li>
						<div>
							<a id="link-about" href="index-dark.html#about">
								<i class="fa fa-user"></i><span>About me</span>
							</a>
						</div>
					</li>
					<li>
						<div>
							<a id="link-work" href="index-dark.html#work">
								<i class="fa fa-briefcase"></i><span>my Portfolio</span>
							</a>
						</div>
					</li>
					<li>
						<div>
							<a id="link-contact" href="index-dark.html#contact">
								<i class="fa fa-envelope-open"></i><span>get in touch</span>
							</a>
						</div>
					</li>
					<li>
						<div>
							<a id="link-blog" href="index-dark.html#blog">
								<i class="fa fa-comments"></i><span>my Blog</span>
							</a>
						</div>
					</li>
				</ul>
				<!-- Mobile Navigation Ends -->
			</div>
		</div>
		<!-- Stretchy Navigation Starts -->
		<div class="cd-stretchy-nav">
			<a class="cd-nav-trigger" href="index-dark.html#0">
				<span aria-hidden="true"></span>
			</a>
			<ul class="stretchy-nav">
				<li class="active"><a href="index-dark.html#home"><span>Home</span></a></li>
				<li><a href="index-dark.html#about"><span>About</span></a></li>
				<li><a href="index-dark.html#works"><span>Portfolio</span></a></li>
				<li><a href="index-dark.html#contact"><span>Contact</span></a></li>
				<li><a href="index-dark.html#blog"><span>Blog</span></a></li>
			</ul>
			<span aria-hidden="true" class="stretchy-nav-bg"></span>
		</div>
		<!-- Stretchy Navigation Ends -->
    </header>
    <!-- Header Ends -->

templates/pages/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>Blog - Istanbul Personal Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link type="text/css" media="all" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link type="text/css" media="all" href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link type="text/css" media="all" href="{% static 'css/style.css' %}" rel="stylesheet">
    <link type="text/css" media="all" href="{% static 'css/skins/yellow.css' %}" rel="stylesheet">

    <!-- Template JS Files -->
    <script src="{% static 'js/modernizr.js' %}"></script>

</head>

<body class="dark blog">
<div class="page">
    <!-- Wrapper Starts -->
    <div class="wrapper">
        <div class="container-fluid page-title">
            <div class="content-banner">
                <h2 class="text-center">
                    <span>Blog </span>
                    <span>Posts</span>
                </h2>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="content">
                    {% for blog in blogs %}
                        <!-- Article Starts -->
                        <article>
                            <a href="blog-post.html"><h4>{{ blog.title }}</h4></a>
                            <!-- Figure Starts -->
                            <figure class="blog-figure">
                                <a href="blog-post.html">
                                    <img class="responsive-img" src="{{ blog.image.url }}" alt="">
                                </a>
                            </figure>
                            <!-- Figure Ends -->
                            <!-- Excerpt Starts -->
                            <div class="blog-excerpt">
                                <p>{{ blog.text }}</p>
                                <a href="{% url 'main:blog_url' %}" class="btn readmore">
                                    <span>Read more</span>
                                </a>
                                <!-- Meta Starts -->
                                <div class="meta">
                                    <span><i class="fa fa-user"></i> <a href="blog.html#">admin</a></span>
                                    <span class="date"><i class="fa fa-calendar"></i> 9 January 2017</span>
                                    <span><i class="fa fa-commenting"></i> <a href="blog-post.html">18</a></span>
                                    <span><i class="fa fa-tags"></i> js, php, html</span>
                                    <span class="permalink"><i class="fa fa-link"></i> <a
                                            href="blog-post.html">permalink</a></span>
                                </div>
                                <!-- Meta Ends -->
                            </div>
                            <!-- Excerpt Ends -->
                        </article>
                        <!-- Article Ends -->
                    {% endfor %}
                    <div class="col-12 mx-auto text-center">
                        <a href="{% url 'main:blog_url' %}" class="btn btn-secondary refresh">
                            <span><i class="fa fa-refresh"></i>load more</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Wrapper Ends -->


<!-- Preloader Starts -->
<div class="preloader">
    <div class="preloader-container">
        <h1>daria</h1>
        <div id="progress-line-container">
            <div class="progress-line"></div>
        </div>
        <h1>taylor</h1>
    </div>
</div>
<!-- Preloader Ends -->
<!-- Template JS Files -->
<script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/transition.js' %}"></script>
<!-- Live Style Switcher JS File - only demo -->
<script src="{% static 'js/styleswitcher.js' %}"></script>

<!-- Main JS Initialization File -->
<script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/pages/blogdetail.html
{% load crispy_forms_filters %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>Blog Post - Istanbul Personal Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <!-- Template CSS Files -->
    <link type="text/css" media="all" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link type="text/css" media="all" href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link type="text/css" media="all" href="{% static 'css/style.css' %}" rel="stylesheet">
    <link type="text/css" media="all" href="{% static 'css/skins/yellow.css' %}" rel="stylesheet">

    <!-- Template JS Files -->
    <script src="{% static 'js/modernizr.js' %}"></script>

</head>

<body class="dark blog">
<div class="page">
    <!-- Wrapper Starts -->
    <div class="wrapper">
        <div class="container-fluid page-title post-title">
            <div class="content-banner">
                <h2 class="text-center">
                    <span>{{ object.title }}</span>
                </h2>
                <div class="meta meta-post-content">
                    <span class="date"><i class="fa fa-calendar"></i>{{ object.date|date:"d M Y" }}</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="content">
                    <!-- Article Starts -->
                    <article>
                        <!-- Excerpt Starts -->
                        <div class="blog-excerpt">
                            <p>{{ object.text }}</p>
                            <!-- Meta Starts -->
                            <div class="meta meta-post-content">
                                <span class="date"><i class="fa fa-calendar"></i>{{ object.date|date:"d M Y" }}</span>
                            </div>
                            <!-- Meta Ends -->
                        </div>
                        <!-- Excerpt Ends -->
                    </article>
                    <!-- Article Ends -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Wrapper Ends -->
<!-- Preloader Starts -->
<div class="preloader">
    <div class="preloader-container">
        <h1>daria</h1>
        <div id="progress-line-container">
            <div class="progress-line"></div>
        </div>
        <h1>taylor</h1>
    </div>
</div>
<!-- Preloader Ends -->
<!-- Template JS Files -->
<script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/transition.js' %}"></script>
<!-- Live Style Switcher JS File - only demo -->
<script src="{% static 'js/styleswitcher.js' %}"></script>

<!-- Main JS Initialization File -->
<script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/pages/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <!-- Main Content Starts -->
    <main id="main">
        <!-- Back To Home Starts [ONLY MOBILE] -->
        <span class="back-mobile" id="back-mobile"><i class="fa fa-arrow-left"></i></span>
        <!-- Back To Home Ends [ONLY MOBILE] -->

        {% include 'pages/home_include/home_include.html' %}

        {% include 'pages/home_include/about.html' %}

        {% include 'pages/home_include/work.html' %}

        {% include 'pages/home_include/contact.html' %}

        {% include 'pages/home_include/blog.html' %}
    </main>
{% endblock %}

templates/pages/home_include/blog.html
{% load static %}
<!-- Blog Section Starts -->
<section id="blog">
    <div class="container page-title text-center">
        <h2 class="text-center">latest <span>posts</span></h2>
        <span class="title-head-subtitle">tips, insights, and best practices about web design and development</span>
    </div>
    <div class="container">
        <div class="row">
            {% for blog in blogs %}
                <!-- Article Starts -->
                <div class="col-12 col-sm-6">
                    <article>
                        <!-- Figure Starts -->
                        <figure class="blog-figure">
                            <a href="{% url 'main:blogdetail_url' blog.id %}">
                                <img class="img-fluid" src="{{ blog.image.url }}" alt="">
                            </a>
                            <div class="post-date"><span>{{ blog.date|date:"d" }}</span>
                                <span>{{ blog.date|date:"M" }}</span>
                            </div>
                        </figure>
                        <!-- Figure Ends -->
                        <a href="{% url 'main:blogdetail_url' blog.id %}">
                            <h4>{{ blog.title }}</h4>
                        </a>
                        <!-- Excerpt Starts -->
                        <div class="blog-excerpt">
                            <p>{{ blog.text }}</p>
                            <a href="{% url 'main:blogdetail_url' blog.id %}"
                               class="btn readmore"><span>Read more</span></a>
                        </div>
                        <!-- Excerpt Ends -->
                    </article>
                </div>
                <!-- Article Ends -->
            {% endfor %}
            <!-- Link To Blog Starts -->
            <div class="col-12 col-sm-12 col-md-12 col-xl-12 col-lg-12 allposts"><a href="{% url 'main:blog_url' %}"
                                                                                    class="btn btn-secondary"><span><i
                    class="fa fa-comments"></i>All posts</span></a>
            </div>
            <!-- Link To Blog Ends -->
        </div>
    </div>
</section>
<!-- Blog Section Ends -->

templates/pages/home_include/contact.html
<!-- Contact Section Starts -->
<section id="contact">
    <div class="contact-container">
        <!-- Main Heading Starts -->
        <div class="container page-title text-center">
            <h2 class="text-center">get <span>in touch</span></h2>
            <span class="title-head-subtitle">I’m always open to discussing product design work or partnerships.</span>
        </div>
        <!-- Main Heading Ends -->
        <div class="container">
            <div class="row contact">
                <!-- Contact Infos Starts -->
                <div class="col-12 col-md-4 col-xl-4 leftside">
                    <ul class="custom-list">
                        <li>
                            <h6 class="font-weight-600"><span class="contact-title">Phone</span><i
                                    class="fa fa-whatsapp"></i><span
                                    class="contact-content">+216 21 184 010</span></h6>
                        </li>
                        <li>
                            <h6 class="font-weight-600"><span class="contact-title">email</span><i
                                    class="fa fa-envelope-o fs-14"></i><span
                                    class="contact-content">info@daria.ua</span>
                            </h6>

                        </li>
                        <li>
                            <h6 class="font-weight-600"><span class="contact-title">instagram</span><i
                                    class="fa fa-instagram"></i><span class="contact-content">daria.198</span>
                            </h6>

                        </li>
                        <li>
                            <h6 class="font-weight-600"><span class="contact-title">Dribbble </span><i
                                    class="fa fa-dribbble"></i><span
                                    class="contact-content">daria.dribble</span></h6>
                        </li>
                    </ul>

                    <!-- Social Media Profiles Starts -->

                    <div class="social">
                        <h6 class="font-weight-600 uppercase">Social Profiles</h6>
                        <ul class="list-inline social social-intro text-center p-none">
                            <li class="facebook"><a title="Facebook" href="index-dark.html#"><i
                                    class="fa fa-facebook"></i></a>
                            </li>
                            <li class="twitter"><a title="Twitter" href="index-dark.html#"><i
                                    class="fa fa-twitter"></i></a>
                            </li>
                            <li class="youtube"><a title="Youtube" href="index-dark.html#"><i
                                    class="fa fa-youtube"></i></a>
                            </li>
                            <li class="dribbble"><a title="Dribbble" href="index-dark.html#"><i
                                    class="fa fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <!-- Social Media Profiles Ends -->
                </div>
                <!-- Contact Infos Ends -->
                <!-- Contact Form Starts -->
                <div class="col-12 col-md-8 col-xl-8 rightside">
                    <p>
                        If you have any suggestion, project or even you want to say Hello.. please fill out the
                        form below and I will reply you shortly.
                    </p>
                    <form class="contactform" method="post"
                          action="{% url 'contact' %}">
                        {% csrf_token %}
                        <div class="row">
                            <!-- Name Field Starts -->
                            <div class="form-group col-xl-6"><i class="fa fa-user prefix"></i>
                                <input id="name" name="name" type="text" class="form-control"
                                       placeholder="YOUR NAME" required>
                            </div>
                            <!-- Name Field Ends -->
                            <!-- Email Field Starts -->
                            <div class="form-group col-xl-6"><i class="fa fa-envelope prefix"></i>
                                <input id="email" type="email" name="email" class="form-control"
                                       placeholder="YOUR EMAIL" required>
                            </div>
                            <!-- Email Field Ends -->
                            <!-- Comment Textarea Starts -->
                            <div class="form-group col-xl-12"><i class="fa fa-comments prefix"></i>
                                <textarea id="comment" name="comment" class="form-control"
                                          placeholder="YOUR MESSAGE" required></textarea>
                            </div>
                            <!-- Comment Textarea Ends -->
                        </div>
                        <!-- Submit Form Button Starts -->
                        <div class="submit-form">
                            <button class="btn button-animated" type="submit" name="send"><span><i
                                    class="fa fa-send"></i> Send Message</span></button>
                        </div>
                        <!-- Submit Form Button Ends -->
                        <div class="form-message"><span
                                class="output_message text-center font-weight-600 uppercase"></span>
                        </div>
                    </form>
                </div>
                <!-- Contact Form Ends -->

            </div>
        </div>
    </div>
</section>
<!-- Contact Section Ends -->

templates/pages/home_include/home_include.html
<!-- Home Section Starts -->
        <section id="home" class="active">
            <!-- Text Rotator Starts -->
            <div class="main-text-container">
                <div class="main-text" id="selector">
                    <h3>Hi there !</h3>
                    <h1 class="ah-headline">
                        I'm
                        <span class="ah-words-wrapper">
							<b class="is-visible">daria taylor</b>
							<b>a web designer</b>
							<b>a blogger</b>
							<b>a freelancer</b>
						</span>
                    </h1>
                    <p>I'm a Freelance UI/UX Designer and Developer based in London, England. I strives to build
                        immersive and beautiful web applications through carefully crafted code and user-centric
                        design.</p>
                    <div class="call-to-actions-home">
                        <div class="text-left">
                            <a href="index-dark.html#about" class="btn link-portfolio-one"><span><i
                                    class="fa fa-user"></i>more about me</span></a>
                            <a href="index-dark.html#work" class="btn btn-secondary link-portfolio-two"><span><i
                                    class="fa fa-suitcase"></i>portfolio</span></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Text Rotator Ends -->
        </section>
<!-- Home Section Ends -->